# Generated by Django 5.2.1 on 2025-05-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(max_length=7),
        ),
    ]
